name: Continuous integration pipeline

on: [push, pull_request]

jobs:
  build-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: npm ci
      - name: test
        run: npm run test-ci

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-ci
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1
    - name: docker build and push to ECR
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/hello-world-web:$IMAGE_TAG .
        docker push $ECR_REGISTRY/hello-world-web:$IMAGE_TAG .
